version: '3'

services:
  auth-service:
    build: ./auth-service
    ports:
      - "3000:3000"
    environment:
      - JWT_SECRET=your_jwt_secret_here
    depends_on:
      - mongo

  reciclavel-metal:
    build: ./reciclavel-metal
    ports:
      - "3002:3002"
    depends_on:
      - mongo

  reciclavel-papel:
    build: ./reciclavel-papel
    ports:
      - "3003:3003"
    depends_on:
      - mongo

  reciclavel-plastico:
    build: ./reciclavel-plastico
    ports:
      - "3004:3004"
    depends_on:
      - mongo

  reciclavel-vidro:
    build: ./reciclavel-vidro
    ports:
      - "3005:3005"

  mongo:
    image: mongo
    ports:
      - "27017:27017"